package com.etong.android.jxbizusedcar.bean;

/**
 * 创造的JSON假数据
 * Created by Administrator on 2016/8/4 0004.
 */
public class UC_MoreJsonData {

    static String mJsonStr = "[{\"titleName\":\"二手车\","
            + "\"itemBeamList\":[{\"itemName\":\"买车\","
            + "\"itemIconName\":\"uc_buy_car\"},"
            + "{\"itemName\":\"卖车\","
            + "\"itemIconName\":\"uc_sell_car\"},"
            + "{\"itemName\":\"车辆估值\","
            + "\"itemIconName\":\"uc_car_assess\"},"
            + "{\"itemName\":\"车辆鉴定\","
            + "\"itemIconName\":\"uc_car_identify\"},"
            + "{\"itemName\":\"汽车金融\","
            + "\"itemIconName\":\"uc_automobile_finance\"},"
            + "{\"itemName\":\"买车攻略\","
            + "\"itemIconName\":\"uc_strategy\"}]},"
           /* + "{\"titleName\":\"社区服务\","
            + "\"itemBeamList\":[{\"itemName\":\"周边服务\","
            + "\"itemIconName\":\"peripheral_service\"},"
            + "{\"itemName\":\"推荐服务\","
            + "\"itemIconName\":\"recommendation_service\"},"
            + "{\"itemName\":\"社区服务记录\","
            + "\"itemIconName\":\"community_service_record\"}]},"
            + "{\"titleName\":\"新车购买\","
            + "\"itemBeamList\":[{\"itemName\":\"找车\","
            + "\"itemIconName\":\"find_car\"},"
            + "{\"itemName\":\"车型对比\","
            + "\"itemIconName\":\"models_comparison\"},"
            + "{\"itemName\":\"试驾预约\","
            + "\"itemIconName\":\"test_drive_appointment\"},"
            + "{\"itemName\":\"订购预约\","
            + "\"itemIconName\":\"order_reservation\"},"
            + "{\"itemName\":\"维保预约\","
            + "\"itemIconName\":\"maintenance_appointment\"},"
            + "{\"itemName\":\"维保进度\","
            + "\"itemIconName\":\"maintenance_progress\"},"
            + "{\"itemName\":\"道路救援\","
            + "\"itemIconName\":\"road_rescue\"}]},"
            + "{\"titleName\":\"汽车金融\","
            + "\"itemBeamList\":[{\"itemName\":\"车贷申请\","
            + "\"itemIconName\":\"car_loan_application\"},"
            + "{\"itemName\":\"车租赁申请\","
            + "\"itemIconName\":\"car_rental_application\"},"
            + "{\"itemName\":\"畅通卡申请\","
            + "\"itemIconName\":\"happy_card_application\"},"
            + "{\"itemName\":\"申请进度\","
            + "\"itemIconName\":\"application_progress\"},"
            + "{\"itemName\":\"贷款记录\","
            + "\"itemIconName\":\"loan_record\"},"
            + "{\"itemName\":\"还款记录\","
            + "\"itemIconName\":\"repayment_history\"},"
            + "{\"itemName\":\"还款提醒\","
            + "\"itemIconName\":\"repayment_reminder\"},"
            + "{\"itemName\":\"逾期记录\","
            + "\"itemIconName\":\"more_overdue\"},"
            + "{\"itemName\":\"融资计算\","
            + "\"itemIconName\":\"financing_calculation\"}]},"
            + "{\"titleName\":\"ETC\","
            + "\"itemBeamList\":[{\"itemName\":\"ETC办卡预约\","
            + "\"itemIconName\":\"etc_card_appointment\"},"
            + "{\"itemName\":\"ETC充值\","
            + "\"itemIconName\":\"etc_recharge\"},"
            + "{\"itemName\":\"余额查询\","
            + "\"itemIconName\":\"balance_query\"},"
            + "{\"itemName\":\"流水记录\","
            + "\"itemIconName\":\"running_account\"},"
            + "{\"itemName\":\"扣款记录\","
            + "\"itemIconName\":\"chargebacks_record\"},"
            + "{\"itemName\":\"发票打印\","
            + "\"itemIconName\":\"invoice_printing\"}]},"
            + "{\"titleName\":\"保险\","
            + "\"itemBeamList\":[{\"itemName\":\"续保预约\","
            + "\"itemIconName\":\"more_renewal_order\"},"
            + "{\"itemName\":\"一键理赔\","
            + "\"itemIconName\":\"onekey_claim\"},"
            + "{\"itemName\":\"续保提醒\","
            + "\"itemIconName\":\"more_renewal_remind\"}]},"
            + "{\"titleName\":\"在线购车\","
            + "\"itemBeamList\":[{\"itemName\":\"底价购车\","
            + "\"itemIconName\":\"car_buying\"},"
            + "{\"itemName\":\"限时购\","
            + "\"itemIconName\":\"more_limited_time\"},"
            + "{\"itemName\":\"促销车\","
            + "\"itemIconName\":\"more_promotion_car\"},"
            + "{\"itemName\":\"汽车服务\","
            + "\"itemIconName\":\"more_car_service\"}]},"
            + "{\"titleName\":\"客运\","
            + "\"itemBeamList\":[{\"itemName\":\"行程发布\","
            + "\"itemIconName\":\"travel_release\"},"
            + "{\"itemName\":\"行程订单接单\","
            + "\"itemIconName\":\"travel_order\"},"
            + "{\"itemName\":\"行程记录\","
            + "\"itemIconName\":\"travel_record\"},"
            + "{\"itemName\":\"投诉维权\","
            + "\"itemIconName\":\"complaints_rights\"}]},"*/
            + "{\"titleName\":\"用车助手\","
            + "\"itemBeamList\":[{\"itemName\":\"违章查询\","
            + "\"itemIconName\":\"violation_query\"},"
            + "{\"itemName\":\"附近加油站\","
            + "\"itemIconName\":\"near_gas_station\"},"
            + "{\"itemName\":\"周边社区服务\","
            + "\"itemIconName\":\"peripheral_community_service\"},"
            + "{\"itemName\":\"附近停车场\","
            + "\"itemIconName\":\"near_park\"}]}]";


    public static String getJsonData() {
        return mJsonStr;
    }

}
