package com.etong.android.jxappusedcar.javabean;

/**
 * 创造的JSON数据
 * Created by Administrator on 2016/8/4 0004.
 */
public class UC_World_FiltrateJsonData {

    static String jsonStr = "[{\"titleName\":\"车龄\","
            + "\"itemNames\":[{\"title\":\"不限\","
            + "\"id\":1},"
            + "{\"title\":\"1年内\","
            + "\"id\":2},"
            + "{\"title\":\"1-3年\","
            + "\"id\":3},"
            + "{\"title\":\"3-5年\","
            + "\"id\":4},"
            + "{\"title\":\"5-8年\","
            + "\"id\":5},"
            + "{\"title\":\"8-10年\","
            + "\"id\":6},"
            + "{\"title\":\"10年以上\","
            + "\"id\":7}]},"
            + "{\"titleName\":\"行驶里程\","
            + "\"itemNames\":[{\"title\":\"不限\","
            + "\"id\":90},"
            + "{\"title\":\"1万以内\","
            + "\"id\":91},"
            + "{\"title\":\"1万-3万\","
            + "\"id\":92},"
            + "{\"title\":\"3万-6万\","
            + "\"id\":93},"
            + "{\"title\":\"6万-10万\","
            + "\"id\":94},"
            + "{\"title\":\"10万以上\","
            + "\"id\":95}]},"
            + "{\"titleName\":\"级别\","
            + "\"itemNames\":[{\"title\":\"微型车\","
            + "\"itemIconName\":\"minicar\","
            + "\"id\":365},"
            + "{\"title\":\"小型车\","
            + "\"itemIconName\":\"smallcar\","
            + "\"id\":366},"
            + "{\"title\":\"紧凑型车\","
            + "\"itemIconName\":\"compact_car\","
            + "\"id\":367},"
            + "{\"title\":\"中型车\","
            + "\"itemIconName\":\"middle_car\","
            + "\"id\":368},"
            + "{\"title\":\"中大型车\","
            + "\"itemIconName\":\"middle_large_car\","
            + "\"id\":369},"
            + "{\"title\":\"豪华车\","
            + "\"itemIconName\":\"largecar\","
            + "\"id\":370},"
            + "{\"title\":\"MPV\","
            + "\"itemIconName\":\"mpv\","
            + "\"id\":371},"
            + "{\"title\":\"SUV\","
            + "\"itemIconName\":\"allsuv\","
            + "\"id\":372},"
            + "{\"title\":\"跑车\","
            + "\"itemIconName\":\"sports_car\","
            + "\"id\":373},"
            + "{\"title\":\"面包车\","
            + "\"itemIconName\":\"small_van\","
            + "\"id\":374},"
            + "{\"title\":\"皮卡\","
            + "\"itemIconName\":\"pickup_truck\","
            + "\"id\":1377}]},"
            + "{\"titleName\":\"国别\","
            + "\"itemNames\":[{\"title\":\"中国\","
            + "\"id\":348},"
            + "{\"title\":\"德国\","
            + "\"id\":349},"
            + "{\"title\":\"日本\","
            + "\"id\":350},"
            + "{\"title\":\"美国\","
            + "\"id\":351},"
            + "{\"title\":\"韩国\","
            + "\"id\":352},"
            + "{\"title\":\"法国\","
            + "\"id\":353},"
            + "{\"title\":\"英国\","
            + "\"id\":354},"
            + "{\"title\":\"意大利\","
            + "\"id\":355}]},"
            + "{\"titleName\":\"结构\","
            + "\"itemNames\":[{\"title\":\"两厢\","
            + "\"id\":8},"
            + "{\"title\":\"三厢\","
            + "\"id\":10},"
            + "{\"title\":\"掀背\","
            + "\"id\":13},"
            + "{\"title\":\"旅行版\","
            + "\"id\":16},"
            + "{\"title\":\"硬顶敞篷车\","
            + "\"id\":14},"
            + "{\"title\":\"软顶敞篷车\","
            + "\"id\":11},"
            + "{\"title\":\"硬顶跑车\","
            + "\"id\":9},"
            + "{\"title\":\"客车\","
            + "\"id\":19},"
            + "{\"title\":\"货车\","
            + "\"id\":17}]},"
            + "{\"titleName\":\"变速箱\","
            + "\"itemNames\":[{\"title\":\"手动\"},"
            + "{\"title\":\"自动\"}]},"
            + "{\"titleName\":\"排量\","
            + "\"itemNames\":[{\"title\":\"1.0L及以下\","
            + "\"outVolEnd\":\"1000\"},"
            + "{\"title\":\"1.1-1.6L\","
            + "\"outVolStar\":\"1100\","
            + "\"outVolEnd\":\"1600\"},"
            + "{\"title\":\"1.7-2.0L\","
            + "\"outVolStar\":\"1700\","
            + "\"outVolEnd\":\"2000\"},"
            + "{\"title\":\"2.1-2.5L\","
            + "\"outVolStar\":\"2100\","
            + "\"outVolEnd\":\"2500\"},"
            + "{\"title\":\"2.6-3.0L\","
            + "\"outVolStar\":\"2600\","
            + "\"outVolEnd\":\"3000\"},"
            + "{\"title\":\"3.1-4.0L\","
            + "\"outVolStar\":\"3100\","
            + "\"outVolEnd\":\"4000\"},"
            + "{\"title\":\"4.0L以上\","
            + "\"outVolStar\":\"4000\"}]}]";

//    ,"
//            +"{\"titleName\":\"属性\","
//            +"\"itemNames\":[\"国产\","
//            + ""进口"]}

    public static String getJsonData() {
        return jsonStr;

    }
}
