package com.etong.android.jxappfours.find_car.filtrate;

/**
 * 创造的JSON数据
 * Created by Administrator on 2016/8/4 0004.
 */
public class Find_Car_OtherJsonData {

    static String jsonStr = "[{\"titleName\":\"国别\","
            + "\"itemNames\":[{\"title\":\"中国\","
            + "\"id\":348},"
            + "{\"title\":\"德国\","
            + "\"id\":349},"
            + "{\"title\":\"日本\","
            + "\"id\":350},"
            + "{\"title\":\"美国\","
            + "\"id\":351},"
            + "{\"title\":\"韩国\","
            + "\"id\":352},"
            + "{\"title\":\"法国\","
            + "\"id\":353},"
            + "{\"title\":\"英国\","
            + "\"id\":354},"
            + "{\"title\":\"意大利\","
            + "\"id\":355}]},"
            + "{\"titleName\":\"结构\","
            + "\"itemNames\":[{\"title\":\"两厢\","
            + "\"id\":8},"
            + "{\"title\":\"三厢\","
            + "\"id\":10},"
            + "{\"title\":\"掀背\","
            + "\"id\":13},"
            + "{\"title\":\"旅行版\","
            + "\"id\":16},"
            + "{\"title\":\"硬顶敞篷车\","
            + "\"id\":14},"
            + "{\"title\":\"软顶敞篷车\","
            + "\"id\":11},"
            + "{\"title\":\"硬顶跑车\","
            + "\"id\":9},"
            + "{\"title\":\"客车\","
            + "\"id\":19},"
            + "{\"title\":\"货车\","
            + "\"id\":17}]},"
            + "{\"titleName\":\"变速箱\","
            + "\"itemNames\":[{\"title\":\"手动\"},"
            + "{\"title\":\"自动\"}]},"
            + "{\"titleName\":\"排量\","
            + "\"itemNames\":[{\"title\":\"1.0L及以下\","
            + "\"outVolEnd\":\"1000\"},"
            + "{\"title\":\"1.1-1.6L\","
            + "\"outVolStar\":\"1100\","
            + "\"outVolEnd\":\"1600\"},"
            + "{\"title\":\"1.7-2.0L\","
            + "\"outVolStar\":\"1700\","
            + "\"outVolEnd\":\"2000\"},"
            + "{\"title\":\"2.1-2.5L\","
            + "\"outVolStar\":\"2100\","
            + "\"outVolEnd\":\"2500\"},"
            + "{\"title\":\"2.6-3.0L\","
            + "\"outVolStar\":\"2600\","
            + "\"outVolEnd\":\"3000\"},"
            + "{\"title\":\"3.1-4.0L\","
            + "\"outVolStar\":\"3100\","
            + "\"outVolEnd\":\"4000\"},"
            + "{\"title\":\"4.0L以上\","
            + "\"outVolStar\":\"4000\"}]}]";

//    ,"
//            +"{\"titleName\":\"属性\","
//            +"\"itemNames\":[\"国产\","
//            + ""进口"]}

    public static String getJsonData() {
        return jsonStr;

    }
}

//+"\"outVolStar\":1100,"
//        +"\"outVolEnd\":1600,"
//        +"\"id\":-1},"
//        + "{\"title\":\"1.7-2.0L\","
//        +"\"outVolStar\":1700,"
//        +"\"outVolEnd\":2000,"
//        +"\"id\":-1},"
//        + "{\"title\":\"2.1-2.5L\","
//        +"\"outVolStar\":2100,"
//        +"\"outVolEnd\":2500,"
//        +"\"id\":-1},"
//        + "{\"title\":\"2.6-3.0L\","
//        +"\"outVolStar\":2600,"
//        +"\"outVolEnd\":3000,"
//        +"\"id\":-1},"
//        + "{\"title\":\"3.1-4.0L\","
//        +"\"outVolStar\":3100,"
//        +"\"outVolEnd\":4000,"
//        +"\"id\":-1},"
//        + "{\"title\":\"4.0L以上\","
//        +"\"outVolStar\":4000,"
//        +"\"outVolEnd\":0,"
//        + "\"id\":-1}]}]";